# Generated by Django 4.2.7 on 2023-11-27 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone_number', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='authData',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.userdata')),
            ],
        ),
    ]
