# Generated by Django 4.2.7 on 2023-12-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_rename_authdata_credentials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='first_name',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='last_name',
            new_name='firstLastName',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='userdata',
            name='dateOfBirth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=2),
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='secondLastName',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='studentId',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
